from __future__ import annotations

import asyncio
from typing import Protocol, Sequence, Tuple, Union, List

from uav_assistant.cross.sockets import TraceFn
from uav_assistant.domain.models import (
    AlgorithmConfiguration,
    ESConfiguration,
    GAConfiguration,
    Waypoint,
    Mission,
    MissionOutcome,
    Path,
    Drone,
    OptimizerError,
    OptimizerStep,
)
from uav_assistant.cross.sockets import TraceQueue


class MissionRepository(Protocol):
    async def get(self, mission_id: int) -> Mission: ...
    async def create(self, mission_name: str | None) -> int: ...
    async def delete(self, mission_id: int) -> None: ...
    async def get_all(self) -> list[Mission]: ...

class WaypointRepository(Protocol):
    async def get(self, waypoint_id: int) -> Waypoint: ...
    async def create(self, mission_id: int, waypoint: Waypoint) -> int: ...
    async def update(self, waypoint: Waypoint) -> None: ...
    async def delete(self, waypoint_id: int) -> None: ...
    async def get_all_by_mission(self, mission_id: int) -> Sequence[Waypoint]: ...
    async def reset_all(self) -> None: ...

class DroneRepository(Protocol):
    async def get(self, drone_id: int) -> Drone: ...
    async def create(self, drone: Drone) -> int: ...
    async def update(self, drone_id: int, drone: Drone) -> None: ...
    async def delete(self, drone_id: int) -> None: ...
    async def get_all(self) -> Sequence[Drone]: ...

class MissionOutcomeRepository(Protocol):
    async def get(self, config_id: int) -> MissionOutcome: ...
    async def create(self, config_id: int, outcome: MissionOutcome) -> int: ...
    async def update(self, config_id: int, outcome: MissionOutcome) -> None: ...
    async def delete(self, config_id: int) -> None: ...

AlgorithmSpecificConfiguration = GAConfiguration | ESConfiguration
AlgorithmRunConfiguration = AlgorithmConfiguration | AlgorithmSpecificConfiguration


class AlgorithmConfigurationRepository(Protocol):
    async def get(self, config_id: int) -> AlgorithmSpecificConfiguration: ...
    async def create(self, config: AlgorithmSpecificConfiguration) -> int: ...
    async def update(
        self,
        config_id: int,
        config: AlgorithmSpecificConfiguration,
    ) -> None: ...
    async def delete(self, config_id: int) -> None: ...

class PathRepository(Protocol):
    async def save( self, mission_id: int, path: Path, generation: int | None = None) -> Path: ...
    async def save_for_mission(self, mission_id: int, path: Path) -> Path: ...
    async def list_by_mission(self, mission_id: int) -> list[Path]: ...
    async def get(self, path_id: int) -> Path: ...
    async def delete_for_mission(self, mission_id: int) -> None: ...


class PathSnapshotRepository(Protocol):
    async def create_many(
        self,
        mission_id: int,
        config_id: int,
        paths: Sequence[Path],
    ) -> None: ...
    async def get_all_by_config(self, config_id: int) -> Sequence[Path]: ...
    async def get_by_generation(
        self,
        config_id: int,
        generation: int,
    ) -> Path: ...
    async def get_minimal_by_config(self, config_id: int) -> Path: ...
    async def delete_by_config(self, config_id: int) -> None: ...


class PathOptimizer(Protocol):
    async def optimize_http(
            self,
            config: AlgorithmRunConfiguration,
            drone: Drone,
            candidates: Sequence[Waypoint],
    ) ->   Tuple[Union[Path | OptimizerError], List[OptimizerStep]]:
        ...

    def optimize_ws(
            self,
            *,
            config: AlgorithmRunConfiguration,
            drone: Drone,
            candidates: Sequence[Waypoint],
            loop: asyncio.AbstractEventLoop,
            queue: TraceQueue,
            trace: TraceFn | None,
    ) -> None:
        ...
