version: "3.9"

services:
  postgres:
    image: postgres:16-alpine
    container_name: uav_postgres
    restart: always
    environment:
      POSTGRES_USER: ${PGROLE}
      POSTGRES_PASSWORD: ${PGPASSWORD}
      POSTGRES_DB: ${PGDATABASE}
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
