"""update with missions

Revision ID: 1e88f36768f4
Revises: 43f3a5fe9e35
Create Date: 2025-11-23 16:50:17.691799

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1e88f36768f4'
down_revision: Union[str, Sequence[str], None] = '43f3a5fe9e35'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('missions',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=100), nullable=True),
    sa.Column('start_waypoint_id', sa.Integer(), nullable=False),
    sa.Column('end_waypoint_id', sa.Integer(), nullable=False),
    sa.Column('k_total', sa.Integer(), nullable=False),
    sa.Column('algo', sa.String(length=20), server_default='GA', nullable=False),
    sa.Column('generations', sa.Integer(), server_default='30', nullable=False),
    sa.Column('population_size', sa.Integer(), server_default='20', nullable=False),
    sa.Column('best_cost', sa.Float(), server_default='0.0', nullable=False),
    sa.Column('status', sa.String(length=20), server_default='COMPLETED', nullable=False),
    sa.ForeignKeyConstraint(['end_waypoint_id'], ['waypoints.id'], ),
    sa.ForeignKeyConstraint(['start_waypoint_id'], ['waypoints.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('mission_drones',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('mission_id', sa.Integer(), nullable=False),
    sa.Column('drone_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['drone_id'], ['drones.id'], ),
    sa.ForeignKeyConstraint(['mission_id'], ['missions.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('mission_id', 'drone_id', name='uq_mission_drone')
    )
    op.create_table('mission_waypoints',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('mission_id', sa.Integer(), nullable=False),
    sa.Column('waypoint_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['mission_id'], ['missions.id'], ),
    sa.ForeignKeyConstraint(['waypoint_id'], ['waypoints.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('mission_id', 'waypoint_id', name='uq_mission_waypoint')
    )
    op.create_table('paths',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('mission_id', sa.Integer(), nullable=False),
    sa.Column('generation', sa.Integer(), server_default='0', nullable=False),
    sa.Column('cost', sa.Float(), server_default='0.0', nullable=False),
    sa.Column('distance_m', sa.Float(), server_default='0.0', nullable=False),
    sa.ForeignKeyConstraint(['mission_id'], ['missions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('path_waypoints',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('path_id', sa.Integer(), nullable=False),
    sa.Column('seq', sa.Integer(), nullable=False),
    sa.Column('waypoint_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['path_id'], ['paths.id'], ),
    sa.ForeignKeyConstraint(['waypoint_id'], ['waypoints.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('path_id', 'seq', name='uq_path_points_path_seq')
    )
    op.drop_column('waypoints', 'visits')
    op.drop_column('waypoints', 'wind_speed')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('waypoints', sa.Column('wind_speed', sa.DOUBLE_PRECISION(precision=53), server_default=sa.text("'4'::double precision"), autoincrement=False, nullable=False))
    op.add_column('waypoints', sa.Column('visits', sa.INTEGER(), server_default=sa.text('2'), autoincrement=False, nullable=False))
    op.drop_table('path_waypoints')
    op.drop_table('paths')
    op.drop_table('mission_waypoints')
    op.drop_table('mission_drones')
    op.drop_table('missions')
    # ### end Alembic commands ###
