"""update from k total to path_size

Revision ID: 26204e269391
Revises: 1e88f36768f4
Create Date: 2025-11-24 15:02:37.337235

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '26204e269391'
down_revision: Union[str, Sequence[str], None] = '1e88f36768f4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('missions', sa.Column('path_size', sa.Integer(), nullable=False))
    op.drop_column('missions', 'k_total')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('missions', sa.Column('k_total', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_column('missions', 'path_size')
    # ### end Alembic commands ###
