"""new db after cleanup

Revision ID: 45a78aed088b
Revises: 26204e269391
Create Date: 2025-11-24 21:00:18.663056

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '45a78aed088b'
down_revision: Union[str, Sequence[str], None] = '26204e269391'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('drones',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=50), server_default='Unnamed Drone', nullable=False),
    sa.Column('speed', sa.Float(), server_default='4.0', nullable=False),
    sa.Column('payload', sa.Float(), server_default='4.0', nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('waypoints',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('latitude', sa.Float(), nullable=False),
    sa.Column('longitude', sa.Float(), nullable=False),
    sa.Column('role', sa.Enum('REQUIRED', 'OPTIONAL', 'STATION', name='waypoint_role'), server_default='OPTIONAL', nullable=False),
    sa.Column('loss_chance', sa.Float(), server_default='0.2', nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name', 'latitude', 'longitude', name='uq_waypoints_name_lat_lon')
    )
    op.create_index('ix_waypoints_lat_lon', 'waypoints', ['latitude', 'longitude'], unique=False)
    op.create_index('ix_waypoints_role', 'waypoints', ['role'], unique=False)
    op.create_table('missions',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=100), nullable=True),
    sa.Column('start_waypoint_id', sa.Integer(), nullable=False),
    sa.Column('end_waypoint_id', sa.Integer(), nullable=False),
    sa.Column('path_size', sa.Integer(), nullable=False),
    sa.Column('algo', sa.String(length=20), server_default='GA', nullable=False),
    sa.Column('generations', sa.Integer(), server_default='30', nullable=False),
    sa.Column('population_size', sa.Integer(), server_default='20', nullable=False),
    sa.Column('best_cost', sa.Float(), server_default='0.0', nullable=False),
    sa.Column('status', sa.String(length=20), server_default='COMPLETED', nullable=False),
    sa.ForeignKeyConstraint(['end_waypoint_id'], ['waypoints.id'], ),
    sa.ForeignKeyConstraint(['start_waypoint_id'], ['waypoints.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('mission_drones',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('mission_id', sa.Integer(), nullable=False),
    sa.Column('drone_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['drone_id'], ['drones.id'], ),
    sa.ForeignKeyConstraint(['mission_id'], ['missions.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('mission_id', 'drone_id', name='uq_mission_drone')
    )
    op.create_table('mission_waypoints',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('mission_id', sa.Integer(), nullable=False),
    sa.Column('waypoint_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['mission_id'], ['missions.id'], ),
    sa.ForeignKeyConstraint(['waypoint_id'], ['waypoints.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('mission_id', 'waypoint_id', name='uq_mission_waypoint')
    )
    op.create_table('paths',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('mission_id', sa.Integer(), nullable=False),
    sa.Column('generation', sa.Integer(), server_default='0', nullable=False),
    sa.Column('cost', sa.Float(), server_default='0.0', nullable=False),
    sa.Column('distance_m', sa.Float(), server_default='0.0', nullable=False),
    sa.ForeignKeyConstraint(['mission_id'], ['missions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('path_waypoints',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('path_id', sa.Integer(), nullable=False),
    sa.Column('seq', sa.Integer(), nullable=False),
    sa.Column('waypoint_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['path_id'], ['paths.id'], ),
    sa.ForeignKeyConstraint(['waypoint_id'], ['waypoints.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('path_id', 'seq', name='uq_path_points_path_seq')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('path_waypoints')
    op.drop_table('paths')
    op.drop_table('mission_waypoints')
    op.drop_table('mission_drones')
    op.drop_table('missions')
    op.drop_index('ix_waypoints_role', table_name='waypoints')
    op.drop_index('ix_waypoints_lat_lon', table_name='waypoints')
    op.drop_table('waypoints')
    op.drop_table('drones')
    # ### end Alembic commands ###
