"""initial schema

Revision ID: 53e61d775d8e
Revises: 
Create Date: 2026-01-30 16:49:20.086717

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '53e61d775d8e'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('drones',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=50), server_default='Unnamed Drone', nullable=False),
    sa.Column('speed', sa.Float(), server_default='4.0', nullable=False),
    sa.Column('payload', sa.Float(), server_default='4.0', nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('waypoints',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('latitude', sa.Float(), nullable=False),
    sa.Column('longitude', sa.Float(), nullable=False),
    sa.Column('role', sa.String(length=20), server_default='REQUIRED', nullable=False),
    sa.Column('wind_speed', sa.Float(), server_default='20.0', nullable=False),
    sa.Column('wind_direction', sa.Float(), server_default='20.0', nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name', 'latitude', 'longitude', name='uq_waypoints_name_lat_lon')
    )
    op.create_index('ix_waypoints_lat_lon', 'waypoints', ['latitude', 'longitude'], unique=False)
    op.create_index('ix_waypoints_role', 'waypoints', ['role'], unique=False)
    op.create_table('missions',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=100), nullable=True),
    sa.Column('start_waypoint_id', sa.Integer(), nullable=False),
    sa.Column('end_waypoint_id', sa.Integer(), nullable=False),
    sa.Column('path_size', sa.Integer(), nullable=False),
    sa.Column('algo', sa.String(length=20), server_default='GA', nullable=False),
    sa.Column('objective', sa.String(length=20), server_default='DISTANCE', nullable=False),
    sa.Column('generations', sa.Integer(), server_default='30', nullable=False),
    sa.Column('population_size', sa.Integer(), server_default='20', nullable=False),
    sa.Column('seed', sa.Integer(), server_default='127', nullable=False),
    sa.Column('mutation_probability', sa.Float(), server_default='0.1', nullable=False),
    sa.Column('keep_elitism', sa.Integer(), server_default='10', nullable=False),
    sa.Column('k_tournament', sa.Integer(), server_default='3', nullable=False),
    sa.Column('sigma0', sa.Float(), server_default='0.25', nullable=False),
    sa.Column('best_cost', sa.Float(), server_default='0.0', nullable=False),
    sa.Column('status', sa.String(length=20), server_default='COMPLETED', nullable=False),
    sa.ForeignKeyConstraint(['end_waypoint_id'], ['waypoints.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['start_waypoint_id'], ['waypoints.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('mission_drones',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('mission_id', sa.Integer(), nullable=False),
    sa.Column('drone_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['drone_id'], ['drones.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['mission_id'], ['missions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('mission_id', 'drone_id', name='uq_mission_drone')
    )
    op.create_table('mission_waypoints',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('mission_id', sa.Integer(), nullable=False),
    sa.Column('waypoint_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['mission_id'], ['missions.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['waypoint_id'], ['waypoints.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('mission_id', 'waypoint_id', name='uq_mission_waypoint')
    )
    op.create_table('path_summaries',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('mission_id', sa.Integer(), nullable=False),
    sa.Column('generation', sa.Integer(), nullable=False),
    sa.Column('cost', sa.Float(), nullable=False),
    sa.Column('total_distance_m', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['mission_id'], ['missions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_path_summaries_mission_gen', 'path_summaries', ['mission_id', 'generation'], unique=False)
    op.create_table('paths',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('mission_id', sa.Integer(), nullable=False),
    sa.Column('generation', sa.Integer(), server_default='0', nullable=False),
    sa.Column('cost', sa.Float(), server_default='0.0', nullable=False),
    sa.Column('distance_m', sa.Float(), server_default='0.0', nullable=False),
    sa.ForeignKeyConstraint(['mission_id'], ['missions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('path_waypoints',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('path_id', sa.Integer(), nullable=False),
    sa.Column('seq', sa.Integer(), nullable=False),
    sa.Column('waypoint_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['path_id'], ['paths.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['waypoint_id'], ['waypoints.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('path_id', 'seq', name='uq_path_points_path_seq')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('path_waypoints')
    op.drop_table('paths')
    op.drop_index('ix_path_summaries_mission_gen', table_name='path_summaries')
    op.drop_table('path_summaries')
    op.drop_table('mission_waypoints')
    op.drop_table('mission_drones')
    op.drop_table('missions')
    op.drop_index('ix_waypoints_role', table_name='waypoints')
    op.drop_index('ix_waypoints_lat_lon', table_name='waypoints')
    op.drop_table('waypoints')
    op.drop_table('drones')
    # ### end Alembic commands ###
