"""dropping autoincrement

Revision ID: 69d618e31720
Revises: 91aa9db91b6f
Create Date: 2025-10-13 12:07:42.718439

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '69d618e31720'
down_revision: Union[str, Sequence[str], None] = '91aa9db91b6f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    op.execute("ALTER TABLE waypoints ALTER COLUMN id DROP IDENTITY IF EXISTS")
    op.execute("ALTER TABLE waypoints ALTER COLUMN id DROP DEFAULT")
    op.execute("DO $$ BEGIN IF EXISTS (SELECT 1 FROM pg_class WHERE relname = 'waypoints_id_seq') THEN "
               "DROP SEQUENCE waypoints_id_seq; END IF; END $$;")

def downgrade() -> None:
    op.execute("ALTER TABLE waypoints ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY")
