"""adding new fields to waypoints and new drones table

Revision ID: 6b0bff6233c7
Revises: 97ecbf59ad7c
Create Date: 2025-10-20 14:57:37.021330

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6b0bff6233c7'
down_revision: Union[str, Sequence[str], None] = '97ecbf59ad7c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('drones',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=50), server_default='Unnamed Drone', nullable=False),
    sa.Column('speed', sa.Float(), server_default='4.0', nullable=False),
    sa.Column('payload', sa.Float(), server_default='4.0', nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.add_column('waypoints', sa.Column('visits', sa.Integer(), server_default='2', nullable=False))
    op.add_column('waypoints', sa.Column('wind_speed', sa.Float(), server_default='4', nullable=False))
    op.add_column('waypoints', sa.Column('loss_chance', sa.Float(), server_default='0.2', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('waypoints', 'loss_chance')
    op.drop_column('waypoints', 'wind_speed')
    op.drop_column('waypoints', 'visits')
    op.drop_table('drones')
    # ### end Alembic commands ###
