"""adding Path_Summary

Revision ID: 6b351ac0e0df
Revises: 898e3fb2ff6c
Create Date: 2026-01-13 09:50:05.568467

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6b351ac0e0df'
down_revision: Union[str, Sequence[str], None] = '898e3fb2ff6c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('path_summaries',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('mission_id', sa.Integer(), nullable=False),
    sa.Column('generation', sa.Integer(), nullable=False),
    sa.Column('cost', sa.Float(), nullable=False),
    sa.Column('total_distance_m', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['mission_id'], ['missions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_path_summaries_mission_gen', 'path_summaries', ['mission_id', 'generation'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_path_summaries_mission_gen', table_name='path_summaries')
    op.drop_table('path_summaries')
    # ### end Alembic commands ###
