"""init schema

Revision ID: 91aa9db91b6f
Revises:
Create Date: 2025-10-12 18:37:50.733569

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '91aa9db91b6f'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('waypoints',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('latitude', sa.Float(), nullable=False),
    sa.Column('longitude', sa.Float(), nullable=False),
    sa.Column('role', sa.Enum('required', 'optional', 'station', name='waypoint_role'), server_default=sa.text("'optional'"), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name', 'latitude', 'longitude', name='uq_waypoints_name_lat_lon')
    )
    op.create_index('ix_waypoints_lat_lon', 'waypoints', ['latitude', 'longitude'], unique=False)
    op.create_index('ix_waypoints_role', 'waypoints', ['role'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_waypoints_role', table_name='waypoints')
    op.drop_index('ix_waypoints_lat_lon', table_name='waypoints')
    op.drop_table('waypoints')
    # ### end Alembic commands ###
